// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwcmcoikzorpjckilawa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Y21jb2lrem9ycGpja2lsYXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MDk0NDAsImV4cCI6MjA1Mzk4NTQ0MH0.Dytc_fKx3xqjf9Emblg-lHm_C8OvHwCeb_SsnYzC9wI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);